apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sample-cmd
spec:
  replicas: 1
  template:
    metadata:
      labels:
        editor: vscode
    spec:
      containers:
      - name: sample-cmd
        image: sample-cmd 